---
- include_vars: 
    file: secrets.yml

#- name: Create work/ dir 
#  file:
#    path: "/home/{{ default_user }}/work"
#    state: directory

- name: Download Micro Workhorses Git
  become: yes
  git:
     repo: https://{{gituser}}@github.com/rguerra/micro-workhorses.git
     dest: "/home/{{default_user}}/micro-workhorses" 
  become: yes
  become_user: root

- name: "Fix permissions"
  file:
    path: "/home/{{ default_user }}/micro-workhorses"
    owner: "{{ default_user }}"
    mode: 0775
    state: directory
    recurse: yes
  become: yes
  become_user: root

- name: Download Jupy Git
  become: yes
  git:
     repo: https://{{gituser}}@github.com/rguerra/jupy.git
     dest: "/home/{{default_user}}/jupy" 
  become: yes
  become_user: root

- name: "Fix permissions"
  file:
    path: "/home/{{ default_user }}/jupy"
    owner: "{{ default_user }}"
    mode: 0775
    state: directory
    recurse: yes
  become: yes
  become_user: root

- name: "Git config"
  git_config:
    name: user.name
    scope: global
    value: rguerra
- name: "Git config"
  git_config:
    name: user.email
    scope: global
    value: rguerr@www-1
