---
- name: Stop apt upgrading services
  become: true
  service:
    name: "{{ item }}"
    state: stopped
  with_items:
    - apt-daily
    - apt-daily.timer
    - apt-daily-upgrade
    - apt-daily-upgrade.timer  
- name: Upgrade apt packages.
  become: true
  apt:
    upgrade: full
  register: apt_action
  delay: 5
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)  
- name: "[developer_tools.yml] Install Global base packages"
  become: true
  apt: name={{ item }} state=present
  with_items:
    - bash-completion
    #- python3-pip
    #- locales
    #- gzip
    #- tar
    #- acl
    #- net-tools
    #- htop
    #- git
    #- vim
    #- build-essential
    #- libssl-dev
    #- libffi-dev
    - python3-dev
  tags:
    - developer_tools
    
- name: "[developer_tools.yml] Upgrade"
  apt: upgrade=dist force_apt_get=yes

#- name: "[deveolper_tools.yml] Install user base packages"
#  apt: name={{ item }} state=present
#  become: "{{ default_user }}"
#  with_items:
#    - bash-completion
#  tags:
#    - developer_tools

#- name: Upgrade pip
#  pip: name=pip state=latest executable=pip3

#- name: Installing docker python library
#  pip:
#    name: docker
#    executable: pip3

- name: Installing docker python library
  pip:
    name: "{{ item }}"
    executable: pip3
  with_items:
    - jupytext
