---
- name: Install base packages
  apt: name={{ item }} state=present
  with_items:
    - bash-completion
    - locales
    - build-essential
    - acl
    - htop
    - git
    - vim
  tags:
    - developer_tools
- name: Install user base packages
  apt: name={{ item }} state=present
  become: "{{ remote_user }}"
  with_items:
    - bash-completion
  tags:
    - developer_tools

