---

- name: Create user
  user:
    name: "{{ remote_user }}"
    comment: "Used to deploy Django"
    state: present
- name: Create .ssh folder
  file:
    path: "/home/{{ remote_user}}/.ssh/"
    state: directory
    mode: 0755
- name: create empty file
  file:
    path: "/home/{{ remote_user}}/.ssh/authorized_keys"
    state: touch
- name: Adding authorized key
  authorized_key:
    user: "{{ remote_user }}"
    state: present
    manage_dir: yes
    key: " {{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Install base packages
  apt: name={{ item }} state=present
  with_items:
    - bash-completion
    - locales
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - supervisor
    - python3-dev
    - python3-pip
  tags:
    - packages
- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
