---

- include_vars: 
    file: secrets.yml
- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  user:
    name: "{{ remote_user }}"
    password: "{{ default_password }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash
#- name: Adding authorized key
#  authorized_key:
#    user: "{{ remote_user }}"
#    state: present
#    manage_dir: yes
#    key: " {{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Copy tmux config
  template:
    src: tmux_conf.j2
    dest: "/home/{{ remote_user }}/.tmux.conf"
    owner: "{{ remote_user }}"

- name: Set up authorized keys for the deployer user
  authorized_key: 
    user: "{{ remote_user }}" 
    key: " {{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  #  key="{{item}}"
  #with_file:
  #  - /home/railsdev/.ssh/id_rsa.pub
- name: Install base packages
  apt: name={{ item }} state=present
  with_items:
    - bash-completion
    - locales
    - build-essential
    - acl
    - ntp
    - htop
    - git
    - supervisor
    - python3-dev
    - python3-pip
    - r-base
  tags:
    - packages
- name: Install user base packages
  apt: name={{ item }} state=present
  become: "{{ remote_user }}"
  with_items:
    - bash-completion
  tags:
    - packages
- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
