---
- include_vars: 
    file: secrets.yml

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present

- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add sudoers users to wheel group
  user:
    name: "{{ remote_user }}"
    password: "{{ default_password }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash
#- name: Adding authorized key
#  authorized_key:
#    user: "{{ remote_user }}"
#    state: present
#    manage_dir: yes
#    key: " {{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- name: Set up authorized keys for the deployer user
  authorized_key: 
    user: "{{ remote_user }}" 
    key: " {{ lookup('file', '~/.ssh/id_rsa.pub') }}"
  #  key="{{item}}"
  #with_file:
  #  - /home/railsdev/.ssh/id_rsa.pub
