---
- include_vars: 
    file: secrets.yml

- name: "[remote_user.yml] Make sure we have a 'wheel' group"
  group:
    name: wheel
    state: present

- name: "[remote_user.yml] Allow 'wheel' group to have passwordless sudo"
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: "[remote_user.yml] Add sudoers users to wheel group"
  user:
    name: "{{ item }}"
    password: "{{ default_password }}"
    groups: wheel
    append: yes
    state: present
    createhome: yes
    shell: /bin/bash
  with_items:
    - "{{ default_user }}"
#- name: Adding authorized key
#  authorized_key:
#    user: "{{ remote_user }}"
#    state: present
#    manage_dir: yes
#    key: " {{ lookup('file', '~/.ssh/id_rsa.pub') }}"
- name: "[remote_user.yml] Set up authorized keys for the deployer user"
  authorized_key: 
    user: "{{ default_user }}" 
    key: " {{ lookup('file', ssh_file) }}"
