---
#- name: conda update -n base -c defaults conda
#  shell: conda update -n base -c defaults conda -y
#  environment:
#    PATH: "{{ conda_prefix }}/bin:$PATH"
#  args:
#    executable: /bin/sh
#  become: yes
#  become_user: root
- name: Installing Jupyterlab 
  shell: conda install jupyterlab -y
  #environment:
  #  PATH: "{{ conda_prefix }}/bin:$PATH"
  args:
    executable: /bin/bash
  become: yes
  become_user: root
- name: Installing npmjs for jupyterlab
  shell: conda install nodejs -y
  #environment:
  #  PATH: "{{ conda_prefix }}/bin:$PATH"
  args:
    executable: /bin/bash
  become: yes
  become_user: root

#- name: Installing Jupyterlab 
#  shell: source /etc/bash.bashrc && conda install -c conda-forge jupyterlab
#  args:
#    executable: /bin/bash
#- name: Installing npmjs doe jupyterlab
#  shell: source /etc/bash.bashrc && conda install -c conda-forge nodejs
#  args:
#    executable: /bin/bash

#- name: conda install npmjs for jupyterlab
#  conda: name=nodejs state=present
#  become: true

