---
- name: Adding enabled site
  template:
    src: nginx_proxy.j2
    dest: /etc/nginx/sites-available/lab
  become: yes
  become_user: root
#- name: ansible create directory example
#  file:
#    path: /etc/nginx/sites-enabled
#    state: directory

- name: Soft Link
  file:
    src: /etc/nginx/sites-available/lab
    dest: /etc/nginx/sites-enabled/lab
    state: link
  become: yes
  become_user: root
- name: restart nginx
  service:
      name: nginx
      state: restarted
  become: yes
  become_user: root
