---

# derived from https://github.com/uchida/ansible-miniconda-role
- name: Install base packages
  apt: name={{ item }} state=present
  with_items:
#    - gzip
    - libcurl4-openssl-dev
    - libssl-dev
    - libxml2-dev
    - libffi-dev
    - libxslt1-dev
#    - libjpeg8-dev
#    - zlib1g-dev
  become: yes
  become_user: root

- name: "[conda.yml] conda installer is downloaded"
  get_url:
    # disable validate-certs due to Python 2 SSL issues
    # we use checksum anyway, so it should be fine
    validate_certs: False
    #url: "https://repo.continuum.io/miniconda/{{conda_installer}}"
    #url: "https://repo.anaconda.com/miniconda/{{ conda_installer }}"
    url: "https://repo.anaconda.com/archive/{{ conda_installer }}"
    dest: "/tmp/{{conda_installer}}"
    checksum: "{{conda_checksum}}"
    mode: 0755

- name: "[conda.yml] miniconda is installed"
  shell:
    '"/tmp/{{ conda_installer }}" -b -p "{{ conda_prefix }}"'
  args:
    creates: "{{ conda_prefix }}"
    executable: /bin/bash
  become: yes
  become_user: root

# add conda to path in two places, so it's always registered
- name: "[conda.yml] add conda to PATH"
  # add it to the front of bashrc, so it's even on noninteractive paths
  lineinfile:
    dest: /etc/bash.bashrc
    state: present
    line: "export PATH={{conda_prefix}}/bin:$PATH"
    insertbefore: BOF
  become: yes
  become_user: root


- name: "[conda.yml] add conda to login PATH"
  # add it to profile, so it's for all login shells
  copy:
    dest: /etc/profile.d/conda.sh
    content: "export PATH={{conda_prefix}}/bin:$PATH"
  become: yes
  become_user: root
  
- name: "[conda.yml] add conda config"
  copy:
    content: "{{ conda_config | to_yaml }}"

    dest: "{{ conda_prefix }}/.condarc"
  become: yes
  become_user: root

- name: "[conda.yml] Add miniconda bin to path"
  become: True
  become_user: root
  shell: echo 'export PATH={{ conda_prefix }}/bin:$PATH' >> /etc/profile

- name: "[conda.yml] read permission for all"
  become: True
  file:
    path: "{{ conda_prefix }}"
    mode: +r
    recurse: yes
  become: yes
  become_user: root

#- name: Upgrading Python
#  shell: conda install python=3.9.4 -y
#  environment:
#    PATH: "{{ conda_prefix }}/bin:$PATH"
#  args:
#    executable: /bin/bash
#  become: yes
#  become_user: root

- name: Python Version
  shell: python --version
  environment:
    PATH: "{{ conda_prefix }}/bin:$PATH"
  args:
    executable: /bin/bash
  become: yes
  become_user: root

#- name: "[conda.yml] update -n base -c defaults conda"
#  shell: conda update -n base -c defaults conda -y
#  environment:
#    PATH: "{{ conda_prefix }}/bin:$PATH"
#  args:
#    executable: /bin/sh
#  become: yes
#  become_user: root

#- name: conda - execution permission for all
#  become: True
#  file:
#    path: "{{ conda_prefix }}/bin"
#    mode: +x
#    recurse: yes
#  become: yes
#  become_user: root
#- name: Conda list
#  shell: conda list
#  environment:
#    PATH: "{{ conda_prefix }}/bin:$PATH"
#  args:
#    executable: /bin/bash
#  become: yes
#  become_user: root

#- name: "[conda.yml] Install python-apt"
#  shell: "conda install -c anaconda-cluster python-apt  -y"
#  environment:
#    SHELL: /bin/bash
#  args:
#    executable: /bin/bash
#  become: yes
#  become_user: root

- name: "[conda.yml] Install Notebook"
  shell: "conda install -c conda-forge {{ item }} -y"
  environment:
    SHELL: /bin/bash
  #  PATH: "{{ conda_prefix }}/bin:$PATH"
  with_items:
    - jupyterlab
    #- nb_conda_kernels
  args:
    executable: /bin/bash
  become: yes
  become_user: root

#- name: Install packages
#  shell: "conda install -c anaconda {{ item }} -y"
#  with_items:
#    - libcurl
#    - openssl 
#    - libxml2 
#    - libffi 
#    - libxslt 
#  environment:
#    SHELL: /bin/bash
#  args:
#    executable: /bin/bash
#  become: yes
#  become_user: root

- name: "[conda.yml] jupyter_client"
  shell: conda install -c anaconda jupyter_client -y
  environment:
    SHELL: /bin/bash
  args:
    executable: /bin/bash
  become: yes
  become_user: root

