---
- hosts: all
  become: yes
  remote_user: root
  gather_facts: False

  vars_files:
    - vars.yml
  pre_tasks:
    - name: "[PRE-TASK] Update apt cache if needed."
      apt: update_cache=yes cache_valid_time=3600
  roles:
    - { role: 'k8s-adm', tags: 'k8s', gather_facts: False, become: yes, become_user: root, become_method: sudo}


