---
- hosts: all
  become: yes
  remote_user: root
  gather_facts: False

  vars_files:
    - vars.yml
  pre_tasks:
    # - name: Stop apt upgrading services
    #   become: true
    #   service:
    #     name: "{{ item }}"
    #     state: stopped
    #   with_items:
    #     - apt-daily
    #     - apt-daily.timer
    #     - apt-daily-upgrade
    #     - apt-daily-upgrade.timer  
    - name: Upgrade apt packages.
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 # One day
      register: apt_action
      delay: 5
      retries: 100
      until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)  
    # - name: Upgrade Ubuntu
    #   shell: "do-release-upgrade"
  roles:
   - { role: 'init', tags: 'init', gather_facts: False, become: yes, become_user: root, become_method: sudo}
   #- { role: 'firewall', tags: 'firewall', gather_facts: False, become: yes, become_user: rguerr, become_method: sudo}
   - { role: 'gitrepos', tags: 'init', gather_facts: False, become: yes, become_user: rguerr, become_method: sudo}
   - { role: 'nodejs', tags: 'nodejs', gather_facts: False, become: yes, become_user: rguerr, become_method: sudo}
   - { role: 'doctl', tags: 'doctl', gather_facts: False, become: yes, become_user: rguerr, become_method: sudo}
   - { role: 'vim', tags: 'vim', gather_facts: False, become: yes, become_user: rguerr, become_method: sudo}
   - { role: 'k8s-adm', tags: 'k8s', gather_facts: False, become: yes, become_user: root, become_method: sudo}
   - { role: 'minikube', tags: 'minikube', gather_facts: False, become: yes, become_user: rguerr, become_method: sudo}


